import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const prestaciones = [
  { nombre: "Barniz de Fluor Boca Completa", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 29900 },
  { nombre: "Biobase Fibras Ribond", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 47900 },
  { nombre: "Blanqueamiento Home Bleaching (No Incluye Cubetas)", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 119900 },
  { nombre: "Blanqueamiento Intraconducto", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 55000 },
  { nombre: "Blanqueamiento Power Bleaching (2 sesiones)", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 149900 },
  { nombre: "Control Implantes + Limpieza + Retiro Rehbilitación", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 49900 },
  { nombre: "Control Semestral + Limpieza", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 28990 },
  { nombre: "Control Y Examen Anual o Semestral", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 15000 },
  { nombre: "Destartraje Boca Completa (+ RX)", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 20000 },
  { nombre: "Destartraje Supra y Subgingival", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 28990 },
  { nombre: "Diagnostico", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 10000 },
  { nombre: "Diseño Sonrisa + Mock Up", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 99900 },
  { nombre: "Elevación de Margen", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 70000 },
  { nombre: "Ferulizado dientes con movilidad", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 42000 },
  { nombre: "Promocion Diagnostico Limpieza Dental (Solo Primera Cita)", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 19900 },
  { nombre: "Protesis Removible Por Arcada", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 240000 },
  { nombre: "Restauracion Compuesta", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 39900 },
  { nombre: "Restauracion Estética", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 70000 },
  { nombre: "Restauración post Endodoncia", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 49900 },
  { nombre: "Restauracion Provisoria", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 22900 },
  { nombre: "Restauración Simple", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 34900 },
  { nombre: "Saldo Anterior", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 0 },
  { nombre: "Sellante Preventivo", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 15900 },
  { nombre: "Sellante Terapeutico (Resina Fluida)", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 22900 },
  { nombre: "Sellantes Boca Completa + Limpieza", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 79900 },
  { nombre: "Sesión Blanqueamiento (General)", categoria: "ACCIONES DE CARÁCTER GENERAL", precio: 80000 },
  { nombre: "Acción Quirurgica", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 20000 },
  { nombre: "Alveoloplastia ( No Incluye Exodoncias)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 150000 },
  { nombre: "Asistencia Quirurgica", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 60000 },
  { nombre: "Biopsia De Mucosa (no Incluye Laboratorio)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 90000 },
  { nombre: "Biopsia Osea", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 120000 },
  { nombre: "Biopsia Por Puncion (no Incluye Laboratorio)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 60000 },
  { nombre: "Biopsia Procesamiento + Informe Histopatologico", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 82800 },
  { nombre: "Cirugia Apical Y Pararradicular Con o Sin Relleno A Retro (Incisivos O Caninos)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 120000 },
  { nombre: "Cirugia Apical Y Pararradicular Con o Sin Relleno A Retro (Premolares Y Molares)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 150000 },
  { nombre: "Cirugía Exodoncias Multiples (Hasta 4 dientes)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 100000 },
  { nombre: "Cirugía Exodoncias Multiples (mas de 4 dientes)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 150000 },
  { nombre: "Elevacion De Piso Del Seno Maxilar (para Instalacion De Implantes)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 450000 },
  { nombre: "Exeresis De Mucocele", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 150000 },
  { nombre: "Exodoncia De 4 Terceros Molares Incluidos o semi-incluidos", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 300000 },
  { nombre: "Exodoncia De Incluidos", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 120000 },
  { nombre: "Exodoncia Mediana Complejidad", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 75000 },
  { nombre: "Exodoncia Simple", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 45000 },
  { nombre: "Fenestración de Incluidos (Para Tracción con Ortodoncia)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 120000 },
  { nombre: "Kit para Cirugía menor", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 60000 },
  { nombre: "Pabellón de Cirugía Menor 120 minutos", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 120000 },
  { nombre: "Pabellón de Cirugía Menor 60 minutos", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 60000 },
  { nombre: "Pabellón de Cirugía Menor 90 minutos", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 90000 },
  { nombre: "Regularización de Reborde Mandibular o Maxilar", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 120000 },
  { nombre: "Tiempo Extra Pabellón (30 minutos)", categoria: "ACCIONES DE CIRUGIA BUCAL Y MAXILOFACIAL", precio: 0 },
  { nombre: "Desobturacion para Retratamiento", categoria: "ACCIONES DE ENDODONCIA", precio: 40000 },
  { nombre: "Endodoncia Incisivos y Caninos", categoria: "ACCIONES DE ENDODONCIA", precio: 170000 },
  { nombre: "Endodoncia Molares", categoria: "ACCIONES DE ENDODONCIA", precio: 235000 },
  { nombre: "Endodoncia Premolares", categoria: "ACCIONES DE ENDODONCIA", precio: 190000 },
  { nombre: "Exploracion caso Atresico", categoria: "ACCIONES DE ENDODONCIA", precio: 40000 },
  { nombre: "Retiro De Poste Metalico", categoria: "ACCIONES DE ENDODONCIA", precio: 40000 },
  { nombre: "Tratamiento conservador", categoria: "ACCIONES DE ENDODONCIA", precio: 70000 },
  { nombre: "Trepanacion por urgencia", categoria: "ACCIONES DE ENDODONCIA", precio: 60000 },
  { nombre: "Aplicación De Flúor Gel Por Sextante", categoria: "ACCIONES DE PERIODONCIA", precio: 19990 },
  { nombre: "Avance De Colgajo, Incisión Perióstica", categoria: "ACCIONES DE PERIODONCIA", precio: 120000 },
  { nombre: "Cirugía ósea Resectiva, Por Sextante", categoria: "ACCIONES DE PERIODONCIA", precio: 120000 },
  { nombre: "Cirugía Periimplantaria De Manejo De Tejidos Blandos, Por Sitio", categoria: "ACCIONES DE PERIODONCIA", precio: 135000 },
  { nombre: "Cobertura Acrílica Post-operatoria", categoria: "ACCIONES DE PERIODONCIA", precio: 75000 },
  { nombre: "Colgajo Para Preservación De Papila", categoria: "ACCIONES DE PERIODONCIA", precio: 135000 },
  { nombre: "Colgajo Periodontal De Acceso, Por Sitio Quirúrgico", categoria: "ACCIONES DE PERIODONCIA", precio: 105000 },
  { nombre: "Colgajo Reposicionado Desplazado Lateral, Coronario O Apical", categoria: "ACCIONES DE PERIODONCIA", precio: 120000 },
  { nombre: "Consulta de Periodoncia", categoria: "ACCIONES DE PERIODONCIA", precio: 22500 },
  { nombre: "Control Post-quirúrgico Con O Sin Retiro De Puntos", categoria: "ACCIONES DE PERIODONCIA", precio: 30000 },
  { nombre: "Control Post-quirúrgico O Recmabio De Cemento Quirúrgico", categoria: "ACCIONES DE PERIODONCIA", precio: 30000 },
  { nombre: "Controles Post-tratamientos (Periodoncia)", categoria: "ACCIONES DE PERIODONCIA", precio: 30000 },
  { nombre: "Curetaje O Debridamiento Subgingival Por Grupo", categoria: "ACCIONES DE PERIODONCIA", precio: 105000 },
  { nombre: "Desgaste Selectivo, por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 75000 },
  { nombre: "Destartraje Subgingival Por Sextante", categoria: "ACCIONES DE PERIODONCIA", precio: 22500 },
  { nombre: "Destartraje Subgingival, Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Destartraje Supragingival Y Limpieza Coronaria Por Sexsante", categoria: "ACCIONES DE PERIODONCIA", precio: 22500 },
  { nombre: "Destartraje Supragingival, Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Disección Quirúrgica Del Injerto En Zona Donante", categoria: "ACCIONES DE PERIODONCIA", precio: 75000 },
  { nombre: "Eliminación Mecánica De Factores Etiológicos Secundarios, Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Enseñanza Y Adiestramiento En Técnicas De Higiene Oral, Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 52500 },
  { nombre: "Estudio Preliminar: Rx, Exámen De Laboratorio, Modelos Etc", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Evaluación Post-terapeútica (con Periodontograma Final E Indices)", categoria: "ACCIONES DE PERIODONCIA", precio: 52500 },
  { nombre: "Exámen De Patología Disfuncional", categoria: "ACCIONES DE PERIODONCIA", precio: 30000 },
  { nombre: "Exámen Periodontal Y Confección De Periodontograma", categoria: "ACCIONES DE PERIODONCIA", precio: 52500 },
  { nombre: "Frenectomía", categoria: "ACCIONES DE PERIODONCIA", precio: 105000 },
  { nombre: "Gingivectomía En Pacientes Con Enfermedades Generales, Por Sextante", categoria: "ACCIONES DE PERIODONCIA", precio: 157500 },
  { nombre: "Gingivectomía En Pacientes Sin Compromiso General, Por Sextante", categoria: "ACCIONES DE PERIODONCIA", precio: 105000 },
  { nombre: "Implante Oseointegrado (no Incluye Valor De Implante)", categoria: "ACCIONES DE PERIODONCIA", precio: 420000 },
  { nombre: "Injerto De Tejido Conectivo, Por Zona", categoria: "ACCIONES DE PERIODONCIA", precio: 127500 },
  { nombre: "Injerto Gingival Libre Por Zona A Injertar", categoria: "ACCIONES DE PERIODONCIA", precio: 135000 },
  { nombre: "Injertos Aloplásticos, No Incluye Material Ni Colgajo", categoria: "ACCIONES DE PERIODONCIA", precio: 75000 },
  { nombre: "Injertos óseos, No Incluye Colgajo De Acceso", categoria: "ACCIONES DE PERIODONCIA", precio: 150000 },
  { nombre: "Interconsulta Con Iforme Escrito", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Interconsulta con Informe Escrito 1 Sesión (Periodoncia)", categoria: "ACCIONES DE PERIODONCIA", precio: 30000 },
  { nombre: "Limpieza Coronaria (eliminación De Pigmentos Y Manchas De Esmalte)", categoria: "ACCIONES DE PERIODONCIA", precio: 52500 },
  { nombre: "Otras Cirugias Mucogingivales", categoria: "ACCIONES DE PERIODONCIA", precio: 105000 },
  { nombre: "Periodontitis Incipiente ( Por Sextante)", categoria: "ACCIONES DE PERIODONCIA", precio: 37500 },
  { nombre: "Periodontitis Moderada", categoria: "ACCIONES DE PERIODONCIA", precio: 45000 },
  { nombre: "Placa De Alivio Oclusal", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Plano De Alivio Oclusal (no Incluye Gastos De Laboratorio", categoria: "ACCIONES DE PERIODONCIA", precio: 112500 },
  { nombre: "Primera Consulta, Exámen Y Diagnóstico (Periodoncia Especialista)", categoria: "ACCIONES DE PERIODONCIA", precio: 30000 },
  { nombre: "Pulido Radicular Avanzadas Y Complejas Por Sesión O Sextante", categoria: "ACCIONES DE PERIODONCIA", precio: 105000 },
  { nombre: "Pulido Radicular Incipientes A Moderadas Por Sesión O Sextante", categoria: "ACCIONES DE PERIODONCIA", precio: 75000 },
  { nombre: "Pulido Radicular Moderadas Avanzadas Por Sesión O Sextante", categoria: "ACCIONES DE PERIODONCIA", precio: 90000 },
  { nombre: "Radectomía U Odontosección Por Pieza (no Incluye Colgajo De Acceso)", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Refuerzo De Técnicas De Higiene Y Motivación", categoria: "ACCIONES DE PERIODONCIA", precio: 45000 },
  { nombre: "Regeneración Tisular Guiada Por Sitio, No Incluye Valor Membrana", categoria: "ACCIONES DE PERIODONCIA", precio: 150000 },
  { nombre: "Sesion De Control De Higiene Oral(revelado + Y/o Evaluacion De Higiene)", categoria: "ACCIONES DE PERIODONCIA", precio: 15000 },
  { nombre: "Sesión De Motivación E Instrucciones En Técnicas De Higiene Oral (por Sesión)", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Técnica de Tunelización para Cubrimiento Radicular (Por Grupo)", categoria: "ACCIONES DE PERIODONCIA", precio: 150000 },
  { nombre: "Terapia De Mantención Con Pulido Radicular Y Tratamiento De Infección", categoria: "ACCIONES DE PERIODONCIA", precio: 105000 },
  { nombre: "Terapia De Mantención De Implantes Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 82500 },
  { nombre: "Terapia De Mantención Periodontal En Enfermedad Inactiva, Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 75000 },
  { nombre: "Toma De Examen Microbiológico", categoria: "ACCIONES DE PERIODONCIA", precio: 15000 },
  { nombre: "Toma De Muestra Placa Bacteriana Y/o Interpretación Exámen Microbiológico", categoria: "ACCIONES DE PERIODONCIA", precio: 30000 },
  { nombre: "Tratamiento De Absceso Periodental", categoria: "ACCIONES DE PERIODONCIA", precio: 37500 },
  { nombre: "Tratamiento De Complicaciones Post-quirurgica, Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 75000 },
  { nombre: "Tratamiento De Hipersensibilidad Dentaria Post-terapia, Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Tratamiento De Urgencia GUNA, Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 67500 },
  { nombre: "Tratamiento Infección Periimplantaria, Por Sesión", categoria: "ACCIONES DE PERIODONCIA", precio: 97500 },
  { nombre: "Tratamiento Químico Del Saco Periodental Por Sextante (no Incluye Valor Materiales)", categoria: "ACCIONES DE PERIODONCIA", precio: 60000 },
  { nombre: "Tunelización Radicular en Comprosmiso de Furca", categoria: "ACCIONES DE PERIODONCIA", precio: 150000 },
  { nombre: "Carilla/Corona EMAX Estética por diente", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 416500 },
  { nombre: "Corona Periferica Completa o Parcial EMAX", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 383200 },
  { nombre: "Diseño de Sonrisa DIGITAL Flujo completo 6 piezas EMAX", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 2499000 },
  { nombre: "Diseño de Sonrisa DIGITAL Flujo completo 8 piezas EMAX", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 3165000 },
  { nombre: "EndoCrown Total o Parcial EMAX", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 383200 },
  { nombre: "Gingivectomia Unitaria", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 35000 },
  { nombre: "Impresion y Diseño de Protesis Total Provisoria sobre Implantes", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 200000 },
  { nombre: "Incrustación EMAX", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 383200 },
  { nombre: "Incrustación o Corona Bloque HIBRYD", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 333200 },
  { nombre: "Protesis Inmediata a Exodoncias", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 90000 },
  { nombre: "Provisorio Adhesivo", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 75000 },
  { nombre: "Rebasado Protesis", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 50000 },
  { nombre: "Recambio CAPS EQUATORS", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 68000 },
  { nombre: "Rehabilitación Plural sobre Implantes por pilar (No Incluye Laboratorio ni Aditamentos)", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 329900 },
  { nombre: "Rehabilitación Unitaria Sobre Implante (No Incluye Laboratorio ni Aditamentos)", categoria: "ACCIONES DE REHABILITACION ORAL DIGITAL", precio: 279900 },
  { nombre: "Aplicación de sellantes en pieza definitiva", categoria: "Acciones Generales", precio: 21388 },
  { nombre: "Aplicación Flúor barniz silano total en adultos", categoria: "Acciones Generales", precio: 68442 },
  { nombre: "Aplicación Flúor en colutorios (tratamiento)", categoria: "Acciones Generales", precio: 13261 },
  { nombre: "Aplicación Flúor Gel total niños y adultos", categoria: "Acciones Generales", precio: 24596 },
  { nombre: "Consultoria y estudios profesionales: 1 hora", categoria: "Acciones Generales", precio: 35290 },
  { nombre: "Control y examen de rigor", categoria: "Acciones Generales", precio: 16000 },
  { nombre: "Estudio Clínico   digital 3D ( con o sin escaneo)", categoria: "Acciones Generales", precio: 209175 },
  { nombre: "Estudio preliminar clínico, radiográfico y de modelos", categoria: "Acciones Generales", precio: 23527 },
  { nombre: "Examen inicial, plan de tratamiento y presupuesto", categoria: "Acciones Generales", precio: 21388 },
  { nombre: "Higiene y profilaxis en adultos", categoria: "Acciones Generales", precio: 23527 },
  { nombre: "Informes periciales", categoria: "Acciones Generales", precio: 35290 },
  { nombre: "Instrucción y control higiene oral adultos", categoria: "Acciones Generales", precio: 13261 },
  { nombre: "Interconsulta con informe escrito (1 sesión)", categoria: "Acciones Generales", precio: 23527 },
  { nombre: "Preventivo #1: Diagnóstico inicial, Presupuesto, Radiografías, etc.", categoria: "Acciones Generales", precio: 47054 },
  { nombre: "Preventivo #2: Diagnóstico inicial, Presupuesto, Radiografías, Flúor, Destartraje, etc", categoria: "Acciones Generales", precio: 94107 },
  { nombre: "\"", categoria: "ACCIONES IMPLANTOLOGIA", precio: 0 },
  { nombre: "Cambio Acondicionador De Tejidos", categoria: "ACCIONES IMPLANTOLOGIA", precio: 30000 },
  { nombre: "Cambio De Tornillos Protésicos (c/u)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 37500 },
  { nombre: "Cirugía Periiplantaria De Tejidos Blandos (no Incluye Insumos)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 135000 },
  { nombre: "Conexión De Implante (no Incluye Valor Aditamientos)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 45000 },
  { nombre: "Desmontaje De Prótesis Y Profilaxis", categoria: "ACCIONES IMPLANTOLOGIA", precio: 120000 },
  { nombre: "Elevación De Piso De Seno Maxilar (para Instalación De Implantes) (no Incluye Insumos)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 450000 },
  { nombre: "Estudio Clínico y Radiográfico Para Implantes", categoria: "ACCIONES IMPLANTOLOGIA", precio: 30000 },
  { nombre: "Exodoncia + Preservación Alveolar con Injerto Oseo (No Incluye Insumos", categoria: "ACCIONES IMPLANTOLOGIA", precio: 150000 },
  { nombre: "Extracción de Implante Compleja", categoria: "ACCIONES IMPLANTOLOGIA", precio: 199000 },
  { nombre: "Extración de Implante Simple", categoria: "ACCIONES IMPLANTOLOGIA", precio: 80000 },
  { nombre: "Guia Quirurgica 3D Planificación Caso Totales", categoria: "ACCIONES IMPLANTOLOGIA", precio: 99000 },
  { nombre: "Implante oseo integrado (Incluye Guia Quirurgica 3D)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 399000 },
  { nombre: "Implante Oseointegrado UNITARIO", categoria: "ACCIONES IMPLANTOLOGIA", precio: 299000 },
  { nombre: "Injerto De Tejido Conectivo (por Zona)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 127500 },
  { nombre: "Planificación Protesis Total Superior Diseño Digital, Protesis Contraste.", categoria: "ACCIONES IMPLANTOLOGIA", precio: 62500 },
  { nombre: "Prótesis Total Implantosportada Mandibular", categoria: "ACCIONES IMPLANTOLOGIA", precio: 950000 },
  { nombre: "Prótesis Total Implantosportada Maxilar", categoria: "ACCIONES IMPLANTOLOGIA", precio: 1350000 },
  { nombre: "Provisorio + Manejo de Tejidos Blandos (No Incluye Aditamentos)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 99000 },
  { nombre: "Provisorio Sobre Implantes (No Incluye Aditamentos)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 80000 },
  { nombre: "Recambio De O Ring O Cap Equator (par)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 52000 },
  { nombre: "Regeneración Osea Guiada (no Incluye Insumos)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 300000 },
  { nombre: "Regeneración Osear Guiada Simultanea a Implante (no Incluye Insumos)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 180000 },
  { nombre: "Rehabilitación sobre Implante UNITARIO", categoria: "ACCIONES IMPLANTOLOGIA", precio: 299000 },
  { nombre: "Tratamiento De De Urgencia (no Incluye Insumos)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 75000 },
  { nombre: "Tratamiento De Infección Periimplantaria Por Sesión (no Incluye Insumos)", categoria: "ACCIONES IMPLANTOLOGIA", precio: 97500 },
  { nombre: "Acción Generica", categoria: "ARANCELES DR BOBADILLA", precio: 0 },
  { nombre: "Blanqueamiento Opalecense Boost 2 sesiones + Destartraje y Profilaxis Boca Completa.", categoria: "ARANCELES DR BOBADILLA", precio: 149900 },
  { nombre: "Destartarje Supra y Subgingival Boca completa", categoria: "ARANCELES DR BOBADILLA", precio: 60000 },
  { nombre: "Destartarje Supragingival + Profilaxis Boca completa", categoria: "ARANCELES DR BOBADILLA", precio: 29900 },
  { nombre: "Diagnostico General, Evaluacion de Radiografias y Educación e Instrucción Habitos de Higiene Oral", categoria: "ARANCELES DR BOBADILLA", precio: 10000 },
  { nombre: "Exodoncia Simple + Control", categoria: "ARANCELES DR BOBADILLA", precio: 45000 },
  { nombre: "Lesion Cervical No Cariosa (V)", categoria: "ARANCELES DR BOBADILLA", precio: 25900 },
  { nombre: "Resina Compuesta Anterior Alta Estetica", categoria: "ARANCELES DR BOBADILLA", precio: 65000 },
  { nombre: "Resina Compuesta Compuesta (II)", categoria: "ARANCELES DR BOBADILLA", precio: 42900 },
  { nombre: "Resina Compuesta Simple (I)", categoria: "ARANCELES DR BOBADILLA", precio: 35900 },
  { nombre: "Sellante Boca Completa + Destartraje Supragingival Boca Completa", categoria: "ARANCELES DR BOBADILLA", precio: 89900 },
  { nombre: "Sellante Preventivo Oclusal", categoria: "ARANCELES DR BOBADILLA", precio: 15000 },
  { nombre: "Sellante Terapeutico Oclusal (RC)", categoria: "ARANCELES DR BOBADILLA", precio: 24900 },
  { nombre: "Alveoloplastía (no incluye exodoncias)", categoria: "Cirugía Maxilofacial", precio: 117634 },
  { nombre: "Biopsia de mucosa (no incluye laboratorio)", categoria: "Cirugía Maxilofacial", precio: 47054 },
  { nombre: "Biopsia de piel (no incluye laboratorio)", categoria: "Cirugía Maxilofacial", precio: 58817 },
  { nombre: "Biopsia ósea", categoria: "Cirugía Maxilofacial", precio: 94107 },
  { nombre: "Biopsia ósea mas instalación de collera (descompresión)", categoria: "Cirugía Maxilofacial", precio: 235268 },
  { nombre: "Cirugía apical y pararradicular con / sin relleno a retro (incisivos o caninos)", categoria: "Cirugía Maxilofacial", precio: 94107 },
  { nombre: "Cirugía apical y pararradicular con / sin relleno a retro (premolares o molares)", categoria: "Cirugía Maxilofacial", precio: 122953 },
  { nombre: "Cirugia complementaria a exodoncia complicada (remoción de agujas u otros c/e)", categoria: "Cirugía Maxilofacial", precio: 188214 },
  { nombre: "Control de especialidad (Cirugía): post quirúrgico o no y con o sin retiro de sutura.", categoria: "Cirugía Maxilofacial", precio: 32082 },
  { nombre: "Enucleación de quiste o tumor simple", categoria: "Cirugía Maxilofacial", precio: 165757 },
  { nombre: "Enucleación de quiste o tumor, con tratamiento del lecho operatorio", categoria: "Cirugía Maxilofacial", precio: 295939 },
  { nombre: "Exeresis de mucocele", categoria: "Cirugía Maxilofacial", precio: 118348 },
  { nombre: "Exodoncia a colgajo", categoria: "Cirugía Maxilofacial", precio: 64164 },
  { nombre: "Exodoncia de 4 terceros molares incluidos", categoria: "Cirugía Maxilofacial", precio: 427760 },
  { nombre: "Exodoncia de piezas incluidas o de implantes previamente instalados", categoria: "Cirugía Maxilofacial", precio: 102662 },
  { nombre: "Exodoncia pieza semi incluida", categoria: "Cirugía Maxilofacial", precio: 94107 },
  { nombre: "Exodoncia simple", categoria: "Cirugía Maxilofacial", precio: 38498 },
  { nombre: "Fenestración compleja", categoria: "Cirugía Maxilofacial", precio: 94107 },
  { nombre: "Fenestración simple", categoria: "Cirugía Maxilofacial", precio: 82344 },
  { nombre: "Interconsulta con informe escrito de cirugía maxilofacial", categoria: "Cirugía Maxilofacial", precio: 35290 },
  { nombre: "Plastía de comunicación bucosinusal o retiro de cuerpo extraño en seno maxilar", categoria: "Cirugía Maxilofacial", precio: 235268 },
  { nombre: "Primera consulta, examen y diagnóstico preliminar en Cirugía maxilofacial", categoria: "Cirugía Maxilofacial", precio: 23527 },
  { nombre: "Recargo por tratamiento fuera de lugar u horario habitual", categoria: "Cirugía Maxilofacial", precio: 47054 },
  { nombre: "Resección o plastía de frenillos, bridas o sinequias", categoria: "Cirugía Maxilofacial", precio: 59886 },
  { nombre: "Tratamiento de comunicación bucosinusal inmediata a exodoncia", categoria: "Cirugía Maxilofacial", precio: 94107 },
  { nombre: "Tratamiento de fractura dentaria (manejo de urgencia)", categoria: "Cirugía Maxilofacial", precio: 47054 },
  { nombre: "Tratamiento de pericoronaritis, alveolorragia y/o alveolitis", categoria: "Cirugía Maxilofacial", precio: 38498 },
  { nombre: "Vestibuloplastía compleja (con injerto u otros sistemas de contención)", categoria: "Cirugía Maxilofacial", precio: 305848 },
  { nombre: "Vestibuloplastía simple", categoria: "Cirugía Maxilofacial", precio: 117634 },
  { nombre: "Plan de atención 5 Restauraciones", categoria: "CONVENIO SUPERMERCADOS", precio: 129950 },
  { nombre: "Plan de atención Limpieza + 4 Restauraciones", categoria: "CONVENIO SUPERMERCADOS", precio: 129950 },
  { nombre: "Plan de atención Preventivo (Sellantes Boca Completa)", categoria: "CONVENIO SUPERMERCADOS", precio: 89950 },
  { nombre: "Plan Implante Unitario (Incluye Pabellón y Rehabilitación)", categoria: "CONVENIO SUPERMERCADOS", precio: 599925 },
  { nombre: "Restauración Unitaria", categoria: "CONVENIO SUPERMERCADOS", precio: 29950 },
  { nombre: "Aislación unitaria compleja", categoria: "Endodoncia", precio: 12334 },
  { nombre: "Apicectomía", categoria: "Endodoncia", precio: 98385 },
  { nombre: "Apicectomía y obturación a retro (incluye MTA)", categoria: "Endodoncia", precio: 183937 },
  { nombre: "Blanqueamiento de pieza desvitalizada: tratamiento químico intra cameral (por sesión)", categoria: "Endodoncia", precio: 49192 },
  { nombre: "Conducto Calcificado (por sesión)", categoria: "Endodoncia", precio: 36860 },
  { nombre: "Control de especialidad (Endodoncia)", categoria: "Endodoncia", precio: 25666 },
  { nombre: "Desobturación para repetir tratamiento", categoria: "Endodoncia", precio: 25666 },
  { nombre: "Desobturación parcial de conductos para anclaje", categoria: "Endodoncia", precio: 19249 },
  { nombre: "Diagnóstico con vitalometría", categoria: "Endodoncia", precio: 17645 },
  { nombre: "Diagnóstico pulpar", categoria: "Endodoncia", precio: 23527 },
  { nombre: "Doble sellado post Endodoncia", categoria: "Endodoncia", precio: 29409 },
  { nombre: "Endodoncia en incisivos y caninos no vitales con lesión", categoria: "Endodoncia", precio: 117634 },
  { nombre: "Endodoncia en incisivos y caninos no vitales sin lesión", categoria: "Endodoncia", precio: 106940 },
  { nombre: "Endodoncia en incisivos y caninos vitales", categoria: "Endodoncia", precio: 98385 },
  { nombre: "Endodoncia en molar inferior no vital con lesión", categoria: "Endodoncia", precio: 192492 },
  { nombre: "Endodoncia en molar inferior no vital sin lesión", categoria: "Endodoncia", precio: 183937 },
  { nombre: "Endodoncia en molar inferior vital", categoria: "Endodoncia", precio: 149716 },
  { nombre: "Endodoncia en molar superior no vital con lesión", categoria: "Endodoncia", precio: 209602 },
  { nombre: "Endodoncia en molar superior no vital sin lesión", categoria: "Endodoncia", precio: 188214 },
  { nombre: "Endodoncia en molar superior vital", categoria: "Endodoncia", precio: 160410 },
  { nombre: "Endodoncia premolares no vitales con lesión", categoria: "Endodoncia", precio: 124050 },
  { nombre: "Endodoncia premolares no vitales sin lesión", categoria: "Endodoncia", precio: 117634 },
  { nombre: "Endodoncia premolares trirradiculares (con lesión)", categoria: "Endodoncia", precio: 186076 },
  { nombre: "Endodoncia premolares trirradiculares (sin lesión)", categoria: "Endodoncia", precio: 160410 },
  { nombre: "Endodoncia premolares vitales", categoria: "Endodoncia", precio: 111218 },
  { nombre: "Ferulización por grupo (por traumatismo dentoalveolar)", categoria: "Endodoncia", precio: 117634 },
  { nombre: "Gingivectomia unitaria para aislación", categoria: "Endodoncia", precio: 24596 },
  { nombre: "Inducción al cierre apical inmediata (por sesion - incluye MTA)", categoria: "Endodoncia", precio: 58817 },
  { nombre: "Inducción al cierre apical mediata (por sesión)", categoria: "Endodoncia", precio: 35290 },
  { nombre: "Instrumentación mecanizada", categoria: "Endodoncia", precio: 39568 },
  { nombre: "Microscopía", categoria: "Endodoncia", precio: 58817 },
  { nombre: "Obturación con técnicas termoplásticas", categoria: "Endodoncia", precio: 47054 },
  { nombre: "Pulpotomía en pieza permanente joven (parcial o total)", categoria: "Endodoncia", precio: 58817 },
  { nombre: "Radectomia y/o hemisección", categoria: "Endodoncia", precio: 94107 },
  { nombre: "Radiografia retroalveolar control de desobturación parcial o total", categoria: "Endodoncia", precio: 6416 },
  { nombre: "Radiografia retroalveolar control obturación", categoria: "Endodoncia", precio: 6416 },
  { nombre: "Radiografia retroalveolar de conductometría", categoria: "Endodoncia", precio: 6416 },
  { nombre: "Reconstrucción para aislamiento", categoria: "Endodoncia", precio: 35290 },
  { nombre: "Recubrimiento pulpar directo o indirecto", categoria: "Endodoncia", precio: 36360 },
  { nombre: "Retiro de espiga colada o preformada del conducto", categoria: "Endodoncia", precio: 52935 },
  { nombre: "Retiro de instrumento fracturado del conducto", categoria: "Endodoncia", precio: 24596 },
  { nombre: "Retratamiento incisivos y caninos con lesión", categoria: "Endodoncia", precio: 199978 },
  { nombre: "Retratamiento incisivos y caninos sin lesión", categoria: "Endodoncia", precio: 194096 },
  { nombre: "Retratamiento molar superior e inferior con lesión apical", categoria: "Endodoncia", precio: 282322 },
  { nombre: "Retratamiento molar superior o inferior sin lesión apical", categoria: "Endodoncia", precio: 258795 },
  { nombre: "Retratamiento premolares con lesión", categoria: "Endodoncia", precio: 217623 },
  { nombre: "Retratamiento premolares sin lesión", categoria: "Endodoncia", precio: 205860 },
  { nombre: "Retratamiento premolares trirradiculares con lesión", categoria: "Endodoncia", precio: 258795 },
  { nombre: "Retratamiento premolares trirradiculares sin lesión", categoria: "Endodoncia", precio: 247031 },
  { nombre: "Sellado de perforaciones y falsas vias", categoria: "Endodoncia", precio: 49192 },
  { nombre: "Sesión de medicación intraconducto", categoria: "Endodoncia", precio: 39568 },
  { nombre: "Tratamiento de revascularización (valor por cada sesión)", categoria: "Endodoncia", precio: 58817 },
  { nombre: "Trepanación de incrustaciones y ferulas", categoria: "Endodoncia", precio: 24596 },
  { nombre: "Trepanación de urgencia", categoria: "Endodoncia", precio: 30728 },
  { nombre: "Vaciamiento de abscesos", categoria: "Endodoncia", precio: 36888 },
  { nombre: "Análisis de estudio tomográfico (RX) y registro fotográfico", categoria: "Implantología", precio: 23527 },
  { nombre: "Ayudantía quirúrgica 25%", categoria: "Implantología", precio: 1176340 },
  { nombre: "Conexión de implante (no incluye valor de aditamentos)", categoria: "Implantología", precio: 36931 },
  { nombre: "Confección de Guías radiográfico quirúrgicas por maxilar (no incluye laboratorio)", categoria: "Implantología", precio: 61597 },
  { nombre: "Control de especialidad (Implantologia)", categoria: "Implantología", precio: 24526 },
  { nombre: "Diagnóstico, Estudio inicial de modelos y plan de tratamiento implantológico", categoria: "Implantología", precio: 59189 },
  { nombre: "Elevación de piso de seno maxilar (para instalación de implantes)", categoria: "Implantología", precio: 368872 },
  { nombre: "Extracciones complejas para implantes", categoria: "Implantología", precio: 51331 },
  { nombre: "Extracciones simples para implantes", categoria: "Implantología", precio: 37074 },
  { nombre: "Injerto tejido conectivo (por zona)", categoria: "Implantología", precio: 99989 },
  { nombre: "Instalación quirúrgica de implantes oseointegrado (no incluye implante)", categoria: "Implantología", precio: 343635 },
  { nombre: "Interconsulta prequirúrgica para implantes", categoria: "Implantología", precio: 35290 },
  { nombre: "Laboratorio de implantes", categoria: "Implantología", precio: 2138800 },
  { nombre: "Laboratorio: Barra sobre implante", categoria: "Implantología", precio: 641640 },
  { nombre: "Laboratorio: Corona sobre Implante Atornillada (por pieza)", categoria: "Implantología", precio: 342208 },
  { nombre: "Laboratorio: Corona sobre Implante Cementada (por pieza)", categoria: "Implantología", precio: 342208 },
  { nombre: "Laboratorio: Guía quirúrgica", categoria: "Implantología", precio: 299432 },
  { nombre: "Laboratorio: Implante oseointegrado (por implante)", categoria: "Implantología", precio: 320820 },
  { nombre: "Laboratorio: Injertos (Auto, Alo, Xenoinjerto - Cualquier tipo)", categoria: "Implantología", precio: 727192 },
  { nombre: "Laboratorio: Insumos Protésicos implante (por pieza)", categoria: "Implantología", precio: 641640 },
  { nombre: "Laboratorio: Intermediario prótesis fija sobre  implante (por pieza)", categoria: "Implantología", precio: 213880 },
  { nombre: "Laboratorio: Membrana de colágeno", categoria: "Implantología", precio: 470536 },
  { nombre: "Laboratorio: Muñón implante", categoria: "Implantología", precio: 171104 },
  { nombre: "Laboratorio: Prótesis Ad Modum (por arcada)", categoria: "Implantología", precio: 1283280 },
  { nombre: "Laboratorio: Provisorio sobre implante (por pieza)", categoria: "Implantología", precio: 96246 },
  { nombre: "Laboratorio: Puros Hueso (cc)", categoria: "Implantología", precio: 727192 },
  { nombre: "Laboratorio: Tornillo (por pieza)", categoria: "Implantología", precio: 42776 },
  { nombre: "Laboratorio: Transfer de implante", categoria: "Implantología", precio: 106940 },
  { nombre: "Manejo de injerto intraoral y extraoral", categoria: "Implantología", precio: 235268 },
  { nombre: "Montaje en articulador y encerado de diagnóstico para implantes (no incluye laboratorio)", categoria: "Implantología", precio: 61597 },
  { nombre: "Pilar muñón sobre implantes", categoria: "Implantología", precio: 128328 },
  { nombre: "Primera consulta, examen y diagnóstico preliminar en Implantologia", categoria: "Implantología", precio: 24596 },
  { nombre: "Toma de injerto intraoral (mentón, rama, tuberosidad) (no incluye insumos)", categoria: "Implantología", precio: 245962 },
  { nombre: "Toma de muestra para examen microbiólogico", categoria: "Implantología", precio: 11763 },
  { nombre: "Corona Unitaria LABORATORIO", categoria: "Laboratorios", precio: 49800 },
  { nombre: "Barra Titanio para 6 Implantes", categoria: "Laboratorios E Insumos", precio: 452000 },
  { nombre: "Barra Zirconio Tipo Toronto para Hibrida 6 Implantes", categoria: "Laboratorios E Insumos", precio: 1077000 },
  { nombre: "Chincheta Ti para ROG", categoria: "Laboratorios E Insumos", precio: 12500 },
  { nombre: "Cilindro Ti para ME", categoria: "Laboratorios E Insumos", precio: 34800 },
  { nombre: "Injerto Oragraft 70/30 0.5CC", categoria: "Laboratorios E Insumos", precio: 107437 },
  { nombre: "Injerto Oragraft 70/30 1CC", categoria: "Laboratorios E Insumos", precio: 148760 },
  { nombre: "Injerto Oragraft 70/30 2CC", categoria: "Laboratorios E Insumos", precio: 230562 },
  { nombre: "Laboratorio Bloque HIBRID", categoria: "Laboratorios E Insumos", precio: 99000 },
  { nombre: "Laboratorio CAD-CAM EMAX Ivoclar Plural", categoria: "Laboratorios E Insumos", precio: 159700 },
  { nombre: "Laboratorio CAD-CAM EMAX Ivoclar UNITARIO", categoria: "Laboratorios E Insumos", precio: 79800 },
  { nombre: "Laboratorio EMAX Unitario", categoria: "Laboratorios E Insumos", precio: 99000 },
  { nombre: "Laboratorio EMAX Unitario SOBRE IMPLANTE", categoria: "Laboratorios E Insumos", precio: 142050 },
  { nombre: "Laboratorio Externo", categoria: "Laboratorios E Insumos", precio: 0 },
  { nombre: "Membrana Ossix Plus 15x20mm", categoria: "Laboratorios E Insumos", precio: 111375 },
  { nombre: "Membrana Ossix Plus 20x30mm", categoria: "Laboratorios E Insumos", precio: 131250 },
  { nombre: "Membrana Ossix Plus 30x40mm", categoria: "Laboratorios E Insumos", precio: 161980 },
  { nombre: "Membrana Ossix Volumax 15x25mm", categoria: "Laboratorios E Insumos", precio: 131250 },
  { nombre: "Membrana Ossix Volumax 25x30", categoria: "Laboratorios E Insumos", precio: 161980 },
  { nombre: "Membrana Viaflex 15x20", categoria: "Laboratorios E Insumos", precio: 102640 },
  { nombre: "Membrana Viaflex 20x30", categoria: "Laboratorios E Insumos", precio: 141320 },
  { nombre: "Membrana Viaflex 30x40", categoria: "Laboratorios E Insumos", precio: 179980 },
  { nombre: "Multi Unit CM Intraoss", categoria: "Laboratorios E Insumos", precio: 47590 },
  { nombre: "Multi-Unit Angulado 17° para Implante dental", categoria: "Laboratorios E Insumos", precio: 59800 },
  { nombre: "Multi-Unit para Implante dental", categoria: "Laboratorios E Insumos", precio: 42800 },
  { nombre: "Pilar Bioestético Cónico", categoria: "Laboratorios E Insumos", precio: 49900 },
  { nombre: "Pilar provisorio para implante dental", categoria: "Laboratorios E Insumos", precio: 36800 },
  { nombre: "Pilares Equator par", categoria: "Laboratorios E Insumos", precio: 182900 },
  { nombre: "Protesis Inmediata Total o Parcial Acrilica", categoria: "Laboratorios E Insumos", precio: 65000 },
  { nombre: "Protesis Removible base metalica", categoria: "Laboratorios E Insumos", precio: 143000 },
  { nombre: "Protesis Total Sobre Implantes Zirconio", categoria: "Laboratorios E Insumos", precio: 2580000 },
  { nombre: "Recambio Caps Equator PAR", categoria: "Laboratorios E Insumos", precio: 68000 },
  { nombre: "Recambio Cofias Equator (dos pilares)", categoria: "Laboratorios E Insumos", precio: 51840 },
  { nombre: "Reparacion Protesis", categoria: "Laboratorios E Insumos", precio: 46350 },
  { nombre: "Smart Box Unidad", categoria: "Laboratorios E Insumos", precio: 78900 },
  { nombre: "T-base Ankylos", categoria: "Laboratorios E Insumos", precio: 148750 },
  { nombre: "T-base para implante dental", categoria: "Laboratorios E Insumos", precio: 37250 },
  { nombre: "T-base Strauman Neodent", categoria: "Laboratorios E Insumos", precio: 89012 },
  { nombre: "Terminación sobre Barra Ti Acrilico Altamente Estético", categoria: "Laboratorios E Insumos", precio: 382000 },
  { nombre: "Tornillo Protesico", categoria: "Laboratorios E Insumos", precio: 18900 },
  { nombre: "Tornillo Ti para ROG", categoria: "Laboratorios E Insumos", precio: 14000 },
  { nombre: "Waterpik", categoria: "Laboratorios E Insumos", precio: 58810 },
  { nombre: "Adaptación a la atención odontólogica", categoria: "Odontopediatría", precio: 36946 },
  { nombre: "Adaptación y preparación de pacientes con necesidades especiales (por sesión)", categoria: "Odontopediatría", precio: 35290 },
  { nombre: "Adaptación y preparación de pacientes de difícil manejo (por sesión)", categoria: "Odontopediatría", precio: 18394 },
  { nombre: "Aplicación de sellantes en pieza temporal", categoria: "Odontopediatría", precio: 18394 },
  { nombre: "Aplicación Flúor barniz silano total en niños", categoria: "Odontopediatría", precio: 64164 },
  { nombre: "Aplicación tópica de barniz de clorhexidina", categoria: "Odontopediatría", precio: 47054 },
  { nombre: "Asesoramiento dietético para control de caries", categoria: "Odontopediatría", precio: 11763 },
  { nombre: "Atención con anestesia general", categoria: "Odontopediatría", precio: 224574 },
  { nombre: "Atención con óxido nitroso (por sesión)", categoria: "Odontopediatría", precio: 128328 },
  { nombre: "Atención con sedación (máximo 4 sesiones) por sesión", categoria: "Odontopediatría", precio: 36860 },
  { nombre: "Consulta odontopediatrica", categoria: "Odontopediatría", precio: 23527 },
  { nombre: "Consulta urgencia odontopediátrica", categoria: "Odontopediatría", precio: 25666 },
  { nombre: "Control niño sano", categoria: "Odontopediatría", precio: 21388 },
  { nombre: "Corona metalica preformada en pieza temporal", categoria: "Odontopediatría", precio: 58817 },
  { nombre: "Coronas de resinas con anclaje sector anterior en pieza temporal", categoria: "Odontopediatría", precio: 35290 },
  { nombre: "Desgaste interferencias cuspideas", categoria: "Odontopediatría", precio: 29409 },
  { nombre: "Destartraje supragingival y limpieza coronaria", categoria: "Odontopediatría", precio: 35290 },
  { nombre: "Educación en Colegios o institución (hora pedagogica)", categoria: "Odontopediatría", precio: 35290 },
  { nombre: "Educación en salud oral", categoria: "Odontopediatría", precio: 23527 },
  { nombre: "Estudio del paciente para ortodoncia interceptiva (modelo - radiografias - fotografias)", categoria: "Odontopediatría", precio: 47054 },
  { nombre: "Exodoncia piezas temporales", categoria: "Odontopediatría", precio: 32082 },
  { nombre: "Exodoncia supernumerario incluido", categoria: "Odontopediatría", precio: 97673 },
  { nombre: "Fenestración mucosas", categoria: "Odontopediatría", precio: 98314 },
  { nombre: "Fenestración óseas", categoria: "Odontopediatría", precio: 82344 },
  { nombre: "Higiene y profilaxis en niños", categoria: "Odontopediatría", precio: 27804 },
  { nombre: "Inactivación de caries en cavidad bucal (cuatro cuadrantes)", categoria: "Odontopediatría", precio: 23527 },
  { nombre: "Inmovilización en traumatismo", categoria: "Odontopediatría", precio: 58817 },
  { nombre: "Instrucción y control higiene oral en niños", categoria: "Odontopediatría", precio: 17645 },
  { nombre: "Interconsulta con odontopediatría", categoria: "Odontopediatría", precio: 29409 },
  { nombre: "Mantenedor de espacio fijo o removible (no incluye laboratorio)", categoria: "Odontopediatría", precio: 47054 },
  { nombre: "Obturación de vidrio ionómero en piezas temporales y permanentes", categoria: "Odontopediatría", precio: 31654 },
  { nombre: "Obturaciones de minima intervención (Técnica ART)", categoria: "Odontopediatría", precio: 35290 },
  { nombre: "Programa de remineralización de caries incipientes por sesión (incluye radiografías diagnós", categoria: "Odontopediatría", precio: 23527 },
  { nombre: "Programa terapeutico para pacientes de alto riesgo cariogenico", categoria: "Odontopediatría", precio: 82344 },
  { nombre: "Protesis en niños (incluye laboratorio)", categoria: "Odontopediatría", precio: 82344 },
  { nombre: "Pulpectomia en pieza temporal anterior", categoria: "Odontopediatría", precio: 29409 },
  { nombre: "Pulpectomia en pieza temporal posterior", categoria: "Odontopediatría", precio: 30940 },
  { nombre: "Pulpotomia en pieza temporal", categoria: "Odontopediatría", precio: 43105 },
  { nombre: "Recubrimiento pulpar directo o indirecto en pieza permanente joven o definitiva", categoria: "Odontopediatría", precio: 29409 },
  { nombre: "Resección de frenillos", categoria: "Odontopediatría", precio: 82344 },
  { nombre: "Resina infiltrante lesión incipiente en piezas permanentes", categoria: "Odontopediatría", precio: 29409 },
  { nombre: "Restauración de fractura coronaria con resina compuesta pieza permanente", categoria: "Odontopediatría", precio: 47054 },
  { nombre: "Restauración de fractura coronaria con resina compuesta pieza temporal", categoria: "Odontopediatría", precio: 35290 },
  { nombre: "Restauración fotocurado pieza temporal: Compuesta Anterior o posterior", categoria: "Odontopediatría", precio: 71436 },
  { nombre: "Restauración fotocurado pieza temporal: Simple Anterior o posterior", categoria: "Odontopediatría", precio: 57106 },
  { nombre: "Tratamiento conducto pieza temporal desvitalizada anterior", categoria: "Odontopediatría", precio: 35290 },
  { nombre: "Tratamiento conducto pieza temporal desvitalizada posterior", categoria: "Odontopediatría", precio: 47054 },
  { nombre: "Tratamiento de mordida abierta o cruzada lateral (no incluye laboratorio)", categoria: "Odontopediatría", precio: 86052 },
  { nombre: "Tratamiento de mordida invertida con o sin aparatos (no incluye laboratorio)", categoria: "Odontopediatría", precio: 86052 },
  { nombre: "Aplicación sellantes fotocurado pieza definitiva (4 molares)", categoria: "Operatoria", precio: 98385 },
  { nombre: "Blanqueamiento dentario con Cubetas (por arcada - estético)", categoria: "Operatoria", precio: 427760 },
  { nombre: "Blanqueamiento dentario con Laser (ambas arcadas - estético)", categoria: "Operatoria", precio: 427760 },
  { nombre: "Blanqueamiento dentario por cuadrante", categoria: "Operatoria", precio: 427760 },
  { nombre: "Carillas directas", categoria: "Operatoria", precio: 128328 },
  { nombre: "Cementación y colocación de perno técnica adhesiva", categoria: "Operatoria", precio: 58817 },
  { nombre: "Cierre de diastema (por sesión)", categoria: "Operatoria", precio: 47054 },
  { nombre: "Confección de muñon de resina", categoria: "Operatoria", precio: 68442 },
  { nombre: "Corona de ceromero muñon vital", categoria: "Operatoria", precio: 111752 },
  { nombre: "Ferulización de un diente", categoria: "Operatoria", precio: 35290 },
  { nombre: "Ferulizaciones de más de un diente (por pieza)", categoria: "Operatoria", precio: 29409 },
  { nombre: "Incrustación Inlay (Cerómero, cerámica y/o porcelana)", categoria: "Operatoria", precio: 97673 },
  { nombre: "Incrustación Onlay u Overlay (Cerómero, cerámica y/o porcelana)", categoria: "Operatoria", precio: 149716 },
  { nombre: "Laboratorio de operatoria", categoria: "Operatoria", precio: 1497160 },
  { nombre: "Laboratorio: cubeta o estampado Superior o Inferior (por arcada)", categoria: "Operatoria", precio: 85552 },
  { nombre: "Laboratorio: Incrustación cualquier material o tipo por pieza (Inlay, Onlay u Overlay)", categoria: "Operatoria", precio: 224574 },
  { nombre: "Laboratorio: Plano o placa de alivio oclusal (cualquier tipo y por arcada)", categoria: "Operatoria", precio: 213880 },
  { nombre: "Obturación de vidrio ionómero en pieza permanente", categoria: "Operatoria", precio: 47054 },
  { nombre: "Primera consulta, examen y diagnóstico preliminar en Operatoria", categoria: "Operatoria", precio: 23527 },
  { nombre: "Recementación de incrustación con ajuste operatorio", categoria: "Operatoria", precio: 73789 },
  { nombre: "Recementación de incrustación sin correcciones", categoria: "Operatoria", precio: 23527 },
  { nombre: "Recementación de incrustación tipo Inlay", categoria: "Operatoria", precio: 70580 },
  { nombre: "Recementación de incrustación tipo Onlay u Overlay", categoria: "Operatoria", precio: 82344 },
  { nombre: "Reconstitución de parcial de coronas o carillas, provisoria o definitivas", categoria: "Operatoria", precio: 41172 },
  { nombre: "Reconstrucción provisoria de corona perdida", categoria: "Operatoria", precio: 61527 },
  { nombre: "Recubrimiento pulpar indirecto con o sin obturación temporal", categoria: "Operatoria", precio: 35290 },
  { nombre: "Recuperación de guia canina por pieza", categoria: "Operatoria", precio: 47054 },
  { nombre: "Remodelación de pieza dentaria con corona atipica", categoria: "Operatoria", precio: 58817 },
  { nombre: "Reobturación de piezas antes de un año", categoria: "Operatoria", precio: 17645 },
  { nombre: "Restauración composite Compleja Anterior (Clase IV) compromiso 2 ángulo en borde incisa", categoria: "Operatoria", precio: 66303 },
  { nombre: "Restauración composite Compleja Posterior (Clase II - tres caras)", categoria: "Operatoria", precio: 66303 },
  { nombre: "Restauración composite Compuesta Anterior (Clase IV)", categoria: "Operatoria", precio: 59886 },
  { nombre: "Restauración composite Compuesta Posterior (Clase II - dos caras)", categoria: "Operatoria", precio: 59886 },
  { nombre: "Restauración composite Simple Anterior (Clase III o V)", categoria: "Operatoria", precio: 53470 },
  { nombre: "Restauración composite Simple Posterior (Clase I - una cara)", categoria: "Operatoria", precio: 53470 },
  { nombre: "Sellantes de resina o vidrio Ionomero", categoria: "Operatoria", precio: 23527 },
  { nombre: "Sensibilidad cervical sin cavidad con vidrio Ionómero y/o barnices", categoria: "Operatoria", precio: 34221 },
  { nombre: "Tratamiento de Remineralización, hipocalcificadas medicamentosa (por sesión)", categoria: "Operatoria", precio: 35290 },
  { nombre: "Arco facial", categoria: "ORTODONCIA", precio: 45289 },
  { nombre: "Axiografia", categoria: "ORTODONCIA", precio: 36467 },
  { nombre: "Cementación de aditamentos (no incluye aditamentos)", categoria: "ORTODONCIA", precio: 11763 },
  { nombre: "Contencion Ortodoncia Inferior", categoria: "ORTODONCIA", precio: 50000 },
  { nombre: "Contención Ortodoncia Superior (Incluye Laboratorio)", categoria: "ORTODONCIA", precio: 90000 },
  { nombre: "Contención ortodóncica: estampada, Hawley o cualquier tipo", categoria: "ORTODONCIA", precio: 47054 },
  { nombre: "Contención rigida lingual o palatina", categoria: "ORTODONCIA", precio: 81274 },
  { nombre: "control aparato ortopédico", categoria: "ORTODONCIA", precio: 30000 },
  { nombre: "Control de evolución", categoria: "ORTODONCIA", precio: 28232 },
  { nombre: "Control mensual Alineadores (Invisalign)", categoria: "ORTODONCIA", precio: 178235 },
  { nombre: "Control mensual contención", categoria: "ORTODONCIA", precio: 34221 },
  { nombre: "Control mensual fijo adulto", categoria: "ORTODONCIA", precio: 72719 },
  { nombre: "Control mensual fijo niño", categoria: "ORTODONCIA", precio: 53470 },
  { nombre: "Control mensual fijo técnica lingual", categoria: "ORTODONCIA", precio: 121199 },
  { nombre: "Control Mensual Ortodoncia", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control mensual removible", categoria: "ORTODONCIA", precio: 49907 },
  { nombre: "Control Ortodoncia Abril", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Agosto", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Diciembre", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Enero", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Febrero", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Julio", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Junio", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Marzo", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Mayo", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Noviembre", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Octubre", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Control Ortodoncia Septiembre", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Deprogramación mediante Jig", categoria: "ORTODONCIA", precio: 155277 },
  { nombre: "Diagnostico, moldes, aparato ortopédico, garantía del aparato por falla en la mano postura", categoria: "ORTODONCIA", precio: 150000 },
  { nombre: "Estudio Ortodoncia", categoria: "ORTODONCIA", precio: 40000 },
  { nombre: "Examen y estudio ortodóncico: radiografías, modelos, fotografías, examen de laboratorio, p", categoria: "ORTODONCIA", precio: 74858 },
  { nombre: "Fuerza extraoral", categoria: "ORTODONCIA", precio: 45629 },
  { nombre: "Higienización por arcada con retiro de aparatos y composite sobre esmalte", categoria: "ORTODONCIA", precio: 48480 },
  { nombre: "Instalación aditamentos para anclaje u otros fines: botón de Nance, rejillas linguales o palati", categoria: "ORTODONCIA", precio: 128328 },
  { nombre: "Instalación aparatos fijos: Autoligado", categoria: "ORTODONCIA", precio: 323494 },
  { nombre: "Instalación aparatos fijos: Cerámicos (técnica programada)", categoria: "ORTODONCIA", precio: 461981 },
  { nombre: "Instalación aparatos fijos: Lingual", categoria: "ORTODONCIA", precio: 677358 },
  { nombre: "Instalación aparatos fijos: Metálicos (técnica programada)", categoria: "ORTODONCIA", precio: 310126 },
  { nombre: "Instalación aparatos removibles (por arcada)", categoria: "ORTODONCIA", precio: 81274 },
  { nombre: "Instalación Arco transpalatino o lingual (barra palatina, no incluye laboratorio)", categoria: "ORTODONCIA", precio: 128328 },
  { nombre: "Instalación de   Aparatos Fijos: Alineadores ( attchments)", categoria: "ORTODONCIA", precio: 1253978 },
  { nombre: "Instalación Disyuntor cualquier tipo: hyrax, cementado o esquelético (no incluye laboratorios", categoria: "ORTODONCIA", precio: 79136 },
  { nombre: "Instalación Ortodoncia Brackets Estéticos", categoria: "ORTODONCIA", precio: 1249750 },
  { nombre: "Instalación Ortodoncia Brackets Metálicos", categoria: "ORTODONCIA", precio: 320000 },
  { nombre: "Instalación Ortodoncia Brackets Metálicos (Promoción 60%)", categoria: "ORTODONCIA", precio: 599900 },
  { nombre: "Instalación propulsor mandibular: cualquier tipo (Herbst, Jasper, Jumper, etc)", categoria: "ORTODONCIA", precio: 142337 },
  { nombre: "Instalación quirúrgica de dispositivos de anclaje temporal: Miniplacas, placas, anclaje esque", categoria: "ORTODONCIA", precio: 641640 },
  { nombre: "Laboratorio de ortodoncia", categoria: "ORTODONCIA", precio: 2138800 },
  { nombre: "Laboratorio: Activadores, aparatos funcionales, Bionators, Monoblock (por arcada)", categoria: "ORTODONCIA", precio: 213880 },
  { nombre: "Laboratorio: Alineadores ambas arcadas", categoria: "ORTODONCIA", precio: 2138800 },
  { nombre: "Laboratorio: Alineadores una arcada", categoria: "ORTODONCIA", precio: 1283280 },
  { nombre: "Laboratorio: Aparato con tornillo", categoria: "ORTODONCIA", precio: 106940 },
  { nombre: "Laboratorio: Aparatos fijos Cerámicos (superior e inferior)", categoria: "ORTODONCIA", precio: 802050 },
  { nombre: "Laboratorio: Aparatos fijos Linguales o Autoligado (superior e inferior)", categoria: "ORTODONCIA", precio: 2138800 },
  { nombre: "Laboratorio: Aparatos fijos Metálicos (superior e inferior)", categoria: "ORTODONCIA", precio: 481230 },
  { nombre: "Laboratorio: Bandas ortodóncicas para piezas definitivas y temporales (por pieza)", categoria: "ORTODONCIA", precio: 32082 },
  { nombre: "Laboratorio: Barra lingual o palatina, Botón Nance, Quadhelix, etc.", categoria: "ORTODONCIA", precio: 213880 },
  { nombre: "Laboratorio: Bionator (por arcada)", categoria: "ORTODONCIA", precio: 106940 },
  { nombre: "Laboratorio: Contención o Aparato simple con o sin tornillo", categoria: "ORTODONCIA", precio: 126189 },
  { nombre: "Laboratorio: Dispositivo de Anclaje esqueletal temporal (Miniplacas y tornillos de miniplacas", categoria: "ORTODONCIA", precio: 641640 },
  { nombre: "Laboratorio: Disyuntor cualquier tipo (por arcada)", categoria: "ORTODONCIA", precio: 299432 },
  { nombre: "Laboratorio: Forsus", categoria: "ORTODONCIA", precio: 256656 },
  { nombre: "Laboratorio: Mantenedor de espacio (por arcada)", categoria: "ORTODONCIA", precio: 85552 },
  { nombre: "Laboratorio: Máscara de Tracción Frontal (cualquier modelo)", categoria: "ORTODONCIA", precio: 256656 },
  { nombre: "Laboratorio: Modelo de yeso Superior o Inferior (por arcada)", categoria: "ORTODONCIA", precio: 21388 },
  { nombre: "Laboratorio: Reparación simple o compleja", categoria: "ORTODONCIA", precio: 53470 },
  { nombre: "Laboratorio: Reposición de Bracket, Banda o Tubo", categoria: "ORTODONCIA", precio: 48123 },
  { nombre: "Laboratorio: TADs o Microtornillo de Ortodoncia (por unidad)", categoria: "ORTODONCIA", precio: 132606 },
  { nombre: "Máscara de tracción frontal: cualquier tipo (Delaire)", categoria: "ORTODONCIA", precio: 292303 },
  { nombre: "Mentonera", categoria: "ORTODONCIA", precio: 45289 },
  { nombre: "Microtornillo", categoria: "ORTODONCIA", precio: 90000 },
  { nombre: "Microtornillos o TADs: evaluación, instalación y retiro", categoria: "ORTODONCIA", precio: 106940 },
  { nombre: "Montaje en articulador (ortodoncia)", categoria: "ORTODONCIA", precio: 67729 },
  { nombre: "Predicción quirúrgica ortognática", categoria: "ORTODONCIA", precio: 142337 },
  { nombre: "Primera consulta, examen y diagnóstico preliminar en Ortodoncia", categoria: "ORTODONCIA", precio: 28232 },
  { nombre: "Quad - Helix: instalación (no incluye laboratorio)", categoria: "ORTODONCIA", precio: 94107 },
  { nombre: "Reestudios con modelos", categoria: "ORTODONCIA", precio: 70580 },
  { nombre: "Reparación contención ortodóntica", categoria: "ORTODONCIA", precio: 24596 },
  { nombre: "Reposición de arcos", categoria: "ORTODONCIA", precio: 21388 },
  { nombre: "Reposición de bandas o tubo", categoria: "ORTODONCIA", precio: 34221 },
  { nombre: "Reposición de brackets cerámicos", categoria: "ORTODONCIA", precio: 24596 },
  { nombre: "Reposición de brackets lingual o autoligado", categoria: "ORTODONCIA", precio: 29943 },
  { nombre: "Reposición de brackets metálicos", categoria: "ORTODONCIA", precio: 21388 },
  { nombre: "Retiro de aparatos fijos (por arcada)", categoria: "ORTODONCIA", precio: 85552 },
  { nombre: "Retiro Ortodoncia", categoria: "ORTODONCIA", precio: 90000 },
  { nombre: "Retiro Ortodoncia Inferior", categoria: "ORTODONCIA", precio: 45000 },
  { nombre: "Retiro Ortodoncia Superior", categoria: "ORTODONCIA", precio: 45000 },
  { nombre: "Set Up modelos", categoria: "ORTODONCIA", precio: 94107 },
  { nombre: "Tratamiento clear aligner: tratamiento semestral", categoria: "ORTODONCIA", precio: 352902 },
  { nombre: "Avance de colgajo, incisión perióstica", categoria: "Periodoncia", precio: 94107 },
  { nombre: "Cirugía de Ancho biológico", categoria: "Periodoncia", precio: 299432 },
  { nombre: "Cirugia ósea resectiva (por sextante)", categoria: "Periodoncia", precio: 94107 },
  { nombre: "Cirugía periimplantaria de tejidos blandos (por sitio)", categoria: "Periodoncia", precio: 105871 },
  { nombre: "Cobertura o placa acrílica palatina post tratamiento", categoria: "Periodoncia", precio: 58817 },
  { nombre: "Colgajo para preservación de papila", categoria: "Periodoncia", precio: 105871 },
  { nombre: "Colgajo periodontal de acceso (por sitio quirúrgico)", categoria: "Periodoncia", precio: 82344 },
  { nombre: "Colgajo reposicionado desplazado lateral, coronario o apical", categoria: "Periodoncia", precio: 98599 },
  { nombre: "Control de especialidad (Periodoncia): post quirúrgico o no y con o sin retiro de sutura.", categoria: "Periodoncia", precio: 25666 },
  { nombre: "Curetaje o debridamiento subgingival (por grupo)", categoria: "Periodoncia", precio: 82344 },
  { nombre: "Desgaste selectivo Dentario o de Plano (por sesión)", categoria: "Periodoncia", precio: 58462 },
  { nombre: "Destartraje subgingival por sesión", categoria: "Periodoncia", precio: 74858 },
  { nombre: "Destartraje subgingival por sextante", categoria: "Periodoncia", precio: 18608 },
  { nombre: "Destartraje supragingival y limpieza coronaria (por sesión)", categoria: "Periodoncia", precio: 44273 },
  { nombre: "Destartraje supragingival y limpieza coronaria (por sextante)", categoria: "Periodoncia", precio: 18608 },
  { nombre: "Disección quirurgica del injerto en zona donante", categoria: "Periodoncia", precio: 58817 },
  { nombre: "Eliminación mecánica de factores etiológicos secundarios (por sesión)", categoria: "Periodoncia", precio: 47054 },
  { nombre: "Evaluación post-térapeutica (con periodontograma final e indices)", categoria: "Periodoncia", precio: 41172 },
  { nombre: "Examen de patología disfuncional", categoria: "Periodoncia", precio: 23527 },
  { nombre: "Examen periodontal y confección de periodontograma", categoria: "Periodoncia", precio: 41172 },
  { nombre: "Examen y estudio periodontal: radiografías, modelos, fotografías, examen de laboratorio, pr", categoria: "Periodoncia", precio: 47054 },
  { nombre: "Ferulización (no incluye material ni laboratorio)", categoria: "Periodoncia", precio: 61456 },
  { nombre: "Frenectomía", categoria: "Periodoncia", precio: 82344 },
  { nombre: "Gingivoplastía en pacientes con compromiso general (por sextante)", categoria: "Periodoncia", precio: 123516 },
  { nombre: "Gingivoplastía en pacientes sin compromiso general (por sextante)", categoria: "Periodoncia", precio: 189427 },
  { nombre: "Injerto de tejido conectivo (por zona)", categoria: "Periodoncia", precio: 104517 },
  { nombre: "Injerto gingival libre por zona a injertar", categoria: "Periodoncia", precio: 111789 },
  { nombre: "Injertos aloplásticos", categoria: "Periodoncia", precio: 58817 },
  { nombre: "Injertos óseos", categoria: "Periodoncia", precio: 117634 },
  { nombre: "Interconsulta con informe periodontal escrito (1 sesión)", categoria: "Periodoncia", precio: 23527 },
  { nombre: "Laboratorio de periodoncia", categoria: "Periodoncia", precio: 1497160 },
  { nombre: "Limpieza coronaria (eliminación de pigmentos y manchas de esmalte)", categoria: "Periodoncia", precio: 44915 },
  { nombre: "Osteotomía (por sitio quirúrgico)", categoria: "Periodoncia", precio: 427760 },
  { nombre: "Otras cirugías mucogingivales", categoria: "Periodoncia", precio: 82344 },
  { nombre: "Plano de relajación o de alivio oclusal  (no incluye laboratorio)", categoria: "Periodoncia", precio: 89117 },
  { nombre: "Primera consulta, examen y diagnóstico preliminar en Periodoncia", categoria: "Periodoncia", precio: 23527 },
  { nombre: "Pulido radicular: periodontitis Avanzadas y complejas (por sesión o sextante)", categoria: "Periodoncia", precio: 81989 },
  { nombre: "Pulido radicular: periodontitis Incipientes (por sesión o sextante)", categoria: "Periodoncia", precio: 64164 },
  { nombre: "Pulido radicular: periodontitis Moderadas (por sesión o sextante)", categoria: "Periodoncia", precio: 70580 },
  { nombre: "Refuerzo de técnicas de higiene y motivación", categoria: "Periodoncia", precio: 42990 },
  { nombre: "Regeneración tisular guiada (por sitio)", categoria: "Periodoncia", precio: 117634 },
  { nombre: "Sesión de control higiene oral (eliminación de pigmentos y manchas de esmalte)", categoria: "Periodoncia", precio: 12478 },
  { nombre: "Sesión de motivación, enseñanza y adiestramiento en técnicas de higiene oral (por sesión)", categoria: "Periodoncia", precio: 41172 },
  { nombre: "Técnica de tunelización para cubrimiento radicular (por grupo)", categoria: "Periodoncia", precio: 124194 },
  { nombre: "Terapia de mantención de implantes (por sesión)", categoria: "Periodoncia", precio: 66303 },
  { nombre: "Terapia de mantención periodontal con pulido radicular y tratamiento de infección", categoria: "Periodoncia", precio: 85552 },
  { nombre: "Terapia de mantención periodontal en enfermedad inactiva (por sesión)", categoria: "Periodoncia", precio: 61456 },
  { nombre: "Toma de muestra placa bacteriana y/o interpretación examen microbiológico", categoria: "Periodoncia", precio: 23527 },
  { nombre: "Tratamiento de absceso periodontal", categoria: "Periodoncia", precio: 30728 },
  { nombre: "Tratamiento de complicaciones post-quirúrgica (por sesión)", categoria: "Periodoncia", precio: 58817 },
  { nombre: "Tratamiento de hipersensibilidad dentaria post-terapia (por sesión)", categoria: "Periodoncia", precio: 47054 },
  { nombre: "Tratamiento de infección periimplantaria (por sesión)", categoria: "Periodoncia", precio: 79136 },
  { nombre: "Tratamiento químico del saco periodontal (por sextante)", categoria: "Periodoncia", precio: 47054 },
  { nombre: "Tunelización radicular en compromiso de furca", categoria: "Periodoncia", precio: 117634 },
  { nombre: "Plan Preventivo (12 sellantes)", categoria: "PLANES DE ATENCIÖN PREFERENTES", precio: 79990 },
  { nombre: "Plan Restaurador Destartraje + 4 Restauraciones", categoria: "PLANES DE ATENCIÖN PREFERENTES", precio: 129990 },
  { nombre: "Restauración Adicional Plan", categoria: "PLANES DE ATENCIÖN PREFERENTES", precio: 29990 },
  { nombre: "Artificios como anclaje de precisión", categoria: "Prótesis Fija", precio: 41172 },
  { nombre: "Barra para protesis sobre implante", categoria: "Prótesis Fija", precio: 307275 },
  { nombre: "Cambio acondicionador de tejidos", categoria: "Prótesis Fija", precio: 23527 },
  { nombre: "Carillas indirectas (cualquier tipo o material)", categoria: "Prótesis Fija", precio: 256656 },
  { nombre: "Control de especialidad (prótesis fija)", categoria: "Prótesis Fija", precio: 25666 },
  { nombre: "Corona inserción Prótesis fija Plural", categoria: "Prótesis Fija", precio: 256656 },
  { nombre: "Corona provisoria de acrílico o policarbonato", categoria: "Prótesis Fija", precio: 64164 },
  { nombre: "Corona provisoria sobre implante", categoria: "Prótesis Fija", precio: 60956 },
  { nombre: "Depromación mediante Jig (protesis fija)", categoria: "Prótesis Fija", precio: 58817 },
  { nombre: "Desmontaje de prótesis y profilaxis", categoria: "Prótesis Fija", precio: 98385 },
  { nombre: "Diseño Digital de Sonrisa", categoria: "Prótesis Fija", precio: 70580 },
  { nombre: "Encerado de diagnóstico", categoria: "Prótesis Fija", precio: 62025 },
  { nombre: "Espiga muñón colado bipartito o pasante", categoria: "Prótesis Fija", precio: 94107 },
  { nombre: "Espiga muñón colado simple", categoria: "Prótesis Fija", precio: 82344 },
  { nombre: "Espiga muñón preformado o postes de fibra de vidrio", categoria: "Prótesis Fija", precio: 106940 },
  { nombre: "Estabilizador mandibular mediante plano deprogramador (mínimo 3 meses)", categoria: "Prótesis Fija", precio: 352902 },
  { nombre: "Examen y estudio rehabilitador: radiografías, modelos, fotografías, examen de laboratorio, p", categoria: "Prótesis Fija", precio: 41172 },
  { nombre: "Frente estético: Maryland o porcelana", categoria: "Prótesis Fija", precio: 129042 },
  { nombre: "Incrustación metálica como inserción en Prótesis fija Plural", categoria: "Prótesis Fija", precio: 129042 },
  { nombre: "Inserciones para puente Maryland", categoria: "Prótesis Fija", precio: 110790 },
  { nombre: "Instalación de broches (O-ring)", categoria: "Prótesis Fija", precio: 188214 },
  { nombre: "Instalación pilar sobre implante", categoria: "Prótesis Fija", precio: 70580 },
  { nombre: "Intermediario dento o implantosoportada en Prótesis fija Plural", categoria: "Prótesis Fija", precio: 178235 },
  { nombre: "Intermediarios para puente Maryland", categoria: "Prótesis Fija", precio: 98528 },
  { nombre: "Laboratorio de protesis fija", categoria: "Prótesis Fija", precio: 1497160 },
  { nombre: "Laboratorio: Aplicación de Porcelana", categoria: "Prótesis Fija", precio: 85552 },
  { nombre: "Laboratorio: Carilla (cualquier tipo: porcelana, disilicato de litio, cerómero, etc.)", categoria: "Prótesis Fija", precio: 256656 },
  { nombre: "Laboratorio: Casquete metálico", categoria: "Prótesis Fija", precio: 85552 },
  { nombre: "Laboratorio: Casquete zirconio", categoria: "Prótesis Fija", precio: 106940 },
  { nombre: "Laboratorio: Corona Provisoria de Acrílico (por pieza)", categoria: "Prótesis Fija", precio: 85552 },
  { nombre: "Laboratorio: Encerado (por pieza)", categoria: "Prótesis Fija", precio: 32082 },
  { nombre: "Laboratorio: Espiga muñón Colada o Preformada (por pieza)", categoria: "Prótesis Fija", precio: 85552 },
  { nombre: "Laboratorio: Incrustación cerómero", categoria: "Prótesis Fija", precio: 213880 },
  { nombre: "Laboratorio: Incrustación metálica", categoria: "Prótesis Fija", precio: 171104 },
  { nombre: "Laboratorio: Incrustación o corona de Inserción (por pieza)", categoria: "Prótesis Fija", precio: 128328 },
  { nombre: "Laboratorio: Incrustación Porcelana, disilicato de litio, etc.", categoria: "Prótesis Fija", precio: 256656 },
  { nombre: "Laboratorio: Intermediario prótesis fija (por pieza)", categoria: "Prótesis Fija", precio: 171104 },
  { nombre: "Laboratorio: Prótesis Fija Unitaria (coronas cualquier tipo y material)", categoria: "Prótesis Fija", precio: 256656 },
  { nombre: "Mock-Up", categoria: "Prótesis Fija", precio: 85552 },
  { nombre: "Montaje en articulador (prótesis fija o removible)", categoria: "Prótesis Fija", precio: 59174 },
  { nombre: "Primera consulta, examen y diagnóstico preliminar en Rehabilitación", categoria: "Prótesis Fija", precio: 17645 },
  { nombre: "Prótesis fija o Corona de porcelana completa o sobre zircónio (casquete cerámico)", categoria: "Prótesis Fija", precio: 278044 },
  { nombre: "Prótesis fija o Corona de porcelana sobre metal", categoria: "Prótesis Fija", precio: 228139 },
  { nombre: "Prótesis fija o Corona metálica completa o 3/4", categoria: "Prótesis Fija", precio: 152924 },
  { nombre: "Protesis fija sobre implante atornillada o cementada", categoria: "Prótesis Fija", precio: 294442 },
  { nombre: "Prótesis Removible provisoria", categoria: "Prótesis Fija", precio: 58817 },
  { nombre: "Prótesis total o parcial implanto retenida", categoria: "Prótesis Fija", precio: 427760 },
  { nombre: "Protesis total o parcial implanto soportada (no incluye broches)", categoria: "Prótesis Fija", precio: 577476 },
  { nombre: "Prótesis total sobre implante (Ad Modum)", categoria: "Prótesis Fija", precio: 1390220 },
  { nombre: "Reapriete o cambio de tornillos prótesicos (c/u) (no incluye valor de tornillo)", categoria: "Prótesis Fija", precio: 32082 },
  { nombre: "Recambio de O'ring o Clip de barra (no incluye valor de aditamentos)", categoria: "Prótesis Fija", precio: 73776 },
  { nombre: "Recementación corona con ajuste operatorio", categoria: "Prótesis Fija", precio: 49192 },
  { nombre: "Recementación corona sin correcciones", categoria: "Prótesis Fija", precio: 30728 },
  { nombre: "Recementación puente con ajuste operatorio", categoria: "Prótesis Fija", precio: 61313 },
  { nombre: "Recementación puente definitivo sin correcciones", categoria: "Prótesis Fija", precio: 42990 },
  { nombre: "Reparación órtesis sobre implante con o sin toma de impresión", categoria: "Prótesis Fija", precio: 73147 },
  { nombre: "Retiro de espiga colada o preformada del conducto", categoria: "Prótesis Fija", precio: 53470 },
  { nombre: "Retiro de prótesis fijas existente", categoria: "Prótesis Fija", precio: 24810 },
  { nombre: "Tallado de retenciones adicionales (cajas, rieleras, etc)", categoria: "Prótesis Fija", precio: 23527 },
  { nombre: "Artificios de anclaje para protesis de complemetación", categoria: "Prótesis Removible", precio: 43020 },
  { nombre: "Control de especialidad (prótesis removible)", categoria: "Prótesis Removible", precio: 25666 },
  { nombre: "Juego de protesis totales superior e inferior acrílico", categoria: "Prótesis Removible", precio: 449148 },
  { nombre: "Laboratorio de protesis removible", categoria: "Prótesis Removible", precio: 1497160 },
  { nombre: "Laboratorio: Cubeta Individual", categoria: "Prótesis Removible", precio: 42776 },
  { nombre: "Laboratorio: Placa de Altura", categoria: "Prótesis Removible", precio: 42776 },
  { nombre: "Laboratorio: Prótesis cucharita", categoria: "Prótesis Removible", precio: 106940 },
  { nombre: "Laboratorio: Prótesis inmediata", categoria: "Prótesis Removible", precio: 256656 },
  { nombre: "Laboratorio: Prótesis Parcial Acrílica (por arcada)", categoria: "Prótesis Removible", precio: 213880 },
  { nombre: "Laboratorio: Prótesis Parcial Metálica (por arcada)", categoria: "Prótesis Removible", precio: 278044 },
  { nombre: "Laboratorio: Prótesis total (por arcada)", categoria: "Prótesis Removible", precio: 213880 },
  { nombre: "Laboratorio: Prótesis Valplass", categoria: "Prótesis Removible", precio: 213880 },
  { nombre: "Laboratorio: Rebasado Total (por prótesis)", categoria: "Prótesis Removible", precio: 149716 },
  { nombre: "Laboratorio: Reparación prótesis con o sin toma de impresión (por arcada)", categoria: "Prótesis Removible", precio: 106940 },
  { nombre: "Prótesis Cucharita", categoria: "Prótesis Removible", precio: 82344 },
  { nombre: "Protesis inmediata", categoria: "Prótesis Removible", precio: 213880 },
  { nombre: "Prótesis Parcial de base Acrílica superior o inferior", categoria: "Prótesis Removible", precio: 184422 },
  { nombre: "Prótesis Parcial de base Metálica superior o inferior", categoria: "Prótesis Removible", precio: 221323 },
  { nombre: "Protesis total inferior de acrílico", categoria: "Prótesis Removible", precio: 227470 },
  { nombre: "Protesis total superior de acrílico", categoria: "Prótesis Removible", precio: 227470 },
  { nombre: "Prótesis total superior o inferior en maxilares con reabsorción extrema", categoria: "Prótesis Removible", precio: 284161 },
  { nombre: "Prótesis Unilateral de base Acrílica superior o inferior", categoria: "Prótesis Removible", precio: 177606 },
  { nombre: "Prótesis Unilateral de base Metálica superior o inferior", categoria: "Prótesis Removible", precio: 196727 },
  { nombre: "Rebasado total", categoria: "Prótesis Removible", precio: 61484 },
  { nombre: "Reparación de prótesis con toma de impresión", categoria: "Prótesis Removible", precio: 36888 },
  { nombre: "Reparación de prótesis sin toma de impresión", categoria: "Prótesis Removible", precio: 24583 },
  { nombre: "Análisis cefalometrico computarizado", categoria: "RADIOLOGIA", precio: 17110 },
  { nombre: "Atlas axis", categoria: "RADIOLOGIA", precio: 17057 },
  { nombre: "ATM transcraneal", categoria: "RADIOLOGIA", precio: 27163 },
  { nombre: "Cavum rino faringeo", categoria: "RADIOLOGIA", precio: 17057 },
  { nombre: "Digitalización", categoria: "RADIOLOGIA", precio: 70580 },
  { nombre: "Ecografia glandulas salivales", categoria: "RADIOLOGIA", precio: 256656 },
  { nombre: "Lateral de mandibula", categoria: "RADIOLOGIA", precio: 17057 },
  { nombre: "Pack RX (4)", categoria: "RADIOLOGIA", precio: 8990 },
  { nombre: "Panorámica", categoria: "RADIOLOGIA", precio: 25666 },
  { nombre: "RADIOGRAFÍA BITE-WING BILATERAL", categoria: "RADIOLOGIA", precio: 24000 },
  { nombre: "RADIOGRAFÍA BITE-WING UNILATERAL", categoria: "RADIOLOGIA", precio: 15000 },
  { nombre: "Radiografía bitewing bilateral adulto (aleta mordida)", categoria: "RADIOLOGIA", precio: 25666 },
  { nombre: "Radiografía bitewing bilateral niños (aleta mordida)", categoria: "RADIOLOGIA", precio: 16041 },
  { nombre: "Radiografía bitewing unilateral adulto (aleta mordida)", categoria: "RADIOLOGIA", precio: 15292 },
  { nombre: "Radiografía bitewing unilateral niños (aleta mordida)", categoria: "RADIOLOGIA", precio: 7646 },
  { nombre: "Radiografía de mano", categoria: "RADIOLOGIA", precio: 16398 },
  { nombre: "Radiografía oclusal", categoria: "RADIOLOGIA", precio: 11763 },
  { nombre: "RADIOGRAFÍA PERIAPICAL", categoria: "RADIOLOGIA", precio: 6000 },
  { nombre: "Radiografía retroalveolar (cualquier técnica)", categoria: "RADIOLOGIA", precio: 6630 },
  { nombre: "Radiografía retroalveolar total", categoria: "RADIOLOGIA", precio: 49192 },
  { nombre: "RADIOGRAFIAS CONVENIO 4 RX", categoria: "RADIOLOGIA", precio: 10000 },
  { nombre: "Reimpresión de radiografía", categoria: "RADIOLOGIA", precio: 11763 },
  { nombre: "Resonancia magnética de ATM", categoria: "RADIOLOGIA", precio: 534700 },
  { nombre: "Resonancia magnética de glándulas", categoria: "RADIOLOGIA", precio: 534700 },
  { nombre: "Senos maxilares", categoria: "RADIOLOGIA", precio: 17057 },
  { nombre: "Senos paranasales", categoria: "RADIOLOGIA", precio: 35290 },
  { nombre: "Set de fotos clinicas", categoria: "RADIOLOGIA", precio: 38498 },
  { nombre: "Sialografia", categoria: "RADIOLOGIA", precio: 136455 },
  { nombre: "Telerradiografia", categoria: "RADIOLOGIA", precio: 17110 },
  { nombre: "Tomografía computarizada o Conebeam de ambos maxilares", categoria: "RADIOLOGIA", precio: 96246 },
  { nombre: "Tomografia computarizada o Conebeam de ATM (una o dos posiciones)", categoria: "RADIOLOGIA", precio: 96246 },
  { nombre: "Tomografía computarizada o Conebeam de Maxilar o Mandíbula (una arcada)", categoria: "RADIOLOGIA", precio: 74858 },
  { nombre: "Tomografia computarizada o Conebeam por zona", categoria: "RADIOLOGIA", precio: 64164 },
  { nombre: "Aplicación de electro física (USS, Tens, Láser) por sesión", categoria: "Trastornos Temporomandibulares", precio: 51331 },
  { nombre: "Artrocentesis (por ATM)", categoria: "Trastornos Temporomandibulares", precio: 256656 },
  { nombre: "Bloqueo anestésico", categoria: "Trastornos Temporomandibulares", precio: 38498 },
  { nombre: "Bloqueo Anestésico Articular", categoria: "Trastornos Temporomandibulares", precio: 106940 },
  { nombre: "Bloqueo Anestésico Extraoral (por sitio de punción)", categoria: "Trastornos Temporomandibulares", precio: 128328 },
  { nombre: "Confección de Dispositivo Intraoral removible (Trastornos Temporomandibulares)", categoria: "Trastornos Temporomandibulares", precio: 526145 },
  { nombre: "Control y/o Consulta de la especialidad (Transtornos temporomandibulares)", categoria: "Trastornos Temporomandibulares", precio: 32082 },
  { nombre: "Diagnóstico, plan de tratamiento y estimación de tiempo", categoria: "Trastornos Temporomandibulares", precio: 55609 },
  { nombre: "Dinámica Mandibular asistida", categoria: "Trastornos Temporomandibulares", precio: 85552 },
  { nombre: "Distracción mandibular asistida", categoria: "Trastornos Temporomandibulares", precio: 53470 },
  { nombre: "Electromiografía de superficie", categoria: "Trastornos Temporomandibulares", precio: 100524 },
  { nombre: "Estudio y explicación de exámenes complementarios en TTM", categoria: "Trastornos Temporomandibulares", precio: 32082 },
  { nombre: "Evaluación funcional", categoria: "Trastornos Temporomandibulares", precio: 74858 },
  { nombre: "Infiltración de medicamentos: Articular o muscular (por sitio)", categoria: "Trastornos Temporomandibulares", precio: 213880 },
  { nombre: "Informes periciales en TTM y DOF", categoria: "Trastornos Temporomandibulares", precio: 128328 },
  { nombre: "Liberación Miofacial", categoria: "Trastornos Temporomandibulares", precio: 128328 },
  { nombre: "Manejo muscular Residual", categoria: "Trastornos Temporomandibulares", precio: 128328 },
  { nombre: "Programa terapéutico articular", categoria: "Trastornos Temporomandibulares", precio: 962460 },
  { nombre: "Programa terapéutico neuromuscular", categoria: "Trastornos Temporomandibulares", precio: 427760 },
  { nombre: "Sonografia", categoria: "Trastornos Temporomandibulares", precio: 79136 },
  { nombre: "Técnicas de movilización mandibular asistida (por sesión)", categoria: "Trastornos Temporomandibulares", precio: 51331 },
  { nombre: "Terapia bioconductual (por sesión)", categoria: "Trastornos Temporomandibulares", precio: 64164 },
  { nombre: "Terapia con punción seca", categoria: "Trastornos Temporomandibulares", precio: 160410 },
  { nombre: "Terapia Farmacológica", categoria: "Trastornos Temporomandibulares", precio: 42776 },
  { nombre: "Tratamiento de urgencia del dolor articular o facial", categoria: "Trastornos Temporomandibulares", precio: 64164 },
  { nombre: "Tratamiento patologia articular", categoria: "Trastornos Temporomandibulares", precio: 571060 },
  { nombre: "Tratamiento patologia articular crónico", categoria: "Trastornos Temporomandibulares", precio: 1469356 },
  { nombre: "Tratamiento patólogia crónica", categoria: "Trastornos Temporomandibulares", precio: 1090788 },
  { nombre: "Tratamiento patologia estructural", categoria: "Trastornos Temporomandibulares", precio: 1469356 },
  { nombre: "Tratamiento patología neuromuscular", categoria: "Trastornos Temporomandibulares", precio: 372151 },
  { nombre: "Tratamiento SAHOS en base a Dispositivos de avance Mandibular (DAM)", categoria: "Trastornos Temporomandibulares", precio: 363596 },
  { nombre: "Otras urgencias", categoria: "Urgencias", precio: 41920 },
  { nombre: "Urgencia de Cirugía (1 sesión)", categoria: "Urgencias", precio: 17320 },
  { nombre: "Urgencia endodóntica (1 sesión)", categoria: "Urgencias", precio: 17320 },
  { nombre: "Urgencia Laboratorio: Coronas Provisorias", categoria: "Urgencias", precio: 16905 },
  { nombre: "Urgencia Laboratorio: Reparación de prótesis con o sin impresión", categoria: "Urgencias", precio: 41570 },
  { nombre: "Urgencia Odontopediatría (1 sesión)", categoria: "Urgencias", precio: 17320 },
  { nombre: "Urgencia Ortodóncica (1 sesión)", categoria: "Urgencias", precio: 17320 },
  { nombre: "Urgencia periodontal (1 sesión)", categoria: "Urgencias", precio: 17320 },
  { nombre: "Urgencia por Implante (1 sesión)", categoria: "Urgencias", precio: 17320 },
  { nombre: "Urgencia trastorno temporomandibular", categoria: "Urgencias", precio: 17320 },
  { nombre: "Urgencia: Coronas provisorias", categoria: "Urgencias", precio: 50841 },
  { nombre: "Urgencia: Exodoncia piezas incluidas (incluye control post tratamiento y retiro de suturas)", categoria: "Urgencias", precio: 117104 },
  { nombre: "Urgencia: Exodoncias a colgajo (incluye control post tratamiento y retiro de suturas)", categoria: "Urgencias", precio: 54614 },
  { nombre: "Urgencia: Exodoncias simples", categoria: "Urgencias", precio: 27240 },
  { nombre: "Urgencia: Radiografía panorámica de urgencia", categoria: "Urgencias", precio: 16539 },
  { nombre: "Urgencia: Radiografía retroalveolar", categoria: "Urgencias", precio: 4434 },
  { nombre: "Urgencia: Recementación de Prótesis fija e incrustaciones", categoria: "Urgencias", precio: 35339 },
  { nombre: "Urgencia: Reparación de prótesis con o sin impresión", categoria: "Urgencias", precio: 59764 },
  { nombre: "Urgencia: Restauraciones Composite anterior", categoria: "Urgencias", precio: 42789 },
  { nombre: "Urgencia: Restauraciones Composite posterior", categoria: "Urgencias", precio: 42789 },
  { nombre: "Urgencia: Tratamiento inicial (1 sesión)", categoria: "Urgencias", precio: 12833 },
  { nombre: "Urgencia: Trepanación de urgencia", categoria: "Urgencias", precio: 29098 },
  { nombre: "Urgencia: Trepanación en pieza permanente joven", categoria: "Urgencias", precio: 29098 },
  { nombre: "Urgencia: Trepanación en pieza temporal", categoria: "Urgencias", precio: 29098 },
  { nombre: "Urgencias a domicilio", categoria: "Urgencias", precio: 23279 },
  { nombre: "Urgencias en hospital", categoria: "Urgencias", precio: 23279 },
]

async function main() {
  console.log(`Importing ${prestaciones.length} prestaciones...`)
  
  const result = await prisma.prestacion.createMany({
    data: prestaciones.map(p => ({
      nombre: p.nombre,
      categoria: p.categoria,
      precio: p.precio,
      duracion: 30,
      activo: true,
    })),
    skipDuplicates: true,
  })

  console.log(`Created ${result.count} new prestaciones.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())