import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireSuperAdmin } from '@/lib/auth'
import { auditAdmin } from '@/lib/audit-admin'
import bcrypt from 'bcryptjs'

export const dynamic = 'force-dynamic'

const DEFAULT_USERNAME = 'Administrador'

// Genera password aleatorio de 12 chars alfanuméricos (sin caracteres
// ambiguos: 0/O, 1/l/I) para el reset por defecto. El super-admin la ve
// una sola vez en la respuesta del endpoint y se la comparte al cliente.
function generateRandomPassword(): string {
  const charset = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789'
  const len = 12
  let out = ''
  const bytes = new Uint8Array(len)
  if (typeof crypto !== 'undefined' && typeof crypto.getRandomValues === 'function') {
    crypto.getRandomValues(bytes)
  } else {
    for (let i = 0; i < len; i++) bytes[i] = Math.floor(Math.random() * 256)
  }
  for (let i = 0; i < len; i++) out += charset[bytes[i] % charset.length]
  return out
}

// POST /api/admin/clinicas/[id]/reset-admin-password
// Body: { newPassword?: string, forceChange?: boolean, username?: string }
// - newPassword: si vacía, usa DEFAULT_PASSWORD ("ADMIN22").
// - forceChange: si true, marca passwordChangedAt=null para forzar cambio en primer login.
// - username: por default "Administrador".
// Si el usuario "Administrador" no existe en la clínica (caso de clínicas
// creadas antes de que el flujo lo generara), se crea en el momento.
export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const admin = await requireSuperAdmin()
  if (!admin) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  const { id } = await params
  const body = await req.json().catch(() => ({}))
  const username = typeof body.username === 'string' && body.username.trim() ? body.username.trim() : DEFAULT_USERNAME
  const newPassword = typeof body.newPassword === 'string' && body.newPassword.length > 0 ? body.newPassword : generateRandomPassword()
  const forceChange = body.forceChange === undefined ? true : Boolean(body.forceChange)

  if (newPassword.length < 6) {
    return NextResponse.json({ error: 'La contraseña debe tener al menos 6 caracteres' }, { status: 400 })
  }

  const clinica = await prisma.clinica.findUnique({ where: { id } })
  if (!clinica) return NextResponse.json({ error: 'Clínica no existe' }, { status: 404 })

  const hash = await bcrypt.hash(newPassword, 10)

  const user = await prisma.user.findFirst({
    where: { clinicaId: clinica.id, username },
  })

  let created = false
  if (user) {
    await prisma.user.update({
      where: { id: user.id },
      data: {
        password: hash,
        activo: true,
        passwordChangedAt: forceChange ? null : new Date(),
      },
    })
  } else {
    await prisma.user.create({
      data: {
        clinicaId: clinica.id,
        name: username,
        username,
        email: null,
        password: hash,
        role: 'admin',
        activo: true,
        passwordChangedAt: forceChange ? null : new Date(),
      },
    })
    created = true
  }

  await auditAdmin({
    actorId: admin.id,
    actorEmail: admin.email,
    action: 'RESET_PASSWORD',
    targetType: 'CLINICA',
    targetId: clinica.id,
    details: {
      clinicaSlug: clinica.slug,
      username,
      forceChange,
      createdNewUser: created,
      passwordWasAutoGenerated: typeof body.newPassword !== 'string' || body.newPassword.length === 0,
    },
    req,
  })

  return NextResponse.json({
    ok: true,
    clinicaSlug: clinica.slug,
    username,
    nuevaPassword: newPassword,
    forzarCambio: forceChange,
    creado: created,
  })
}
